//! Tauri's codegen, plus the one thing this crate refuses to be built without: `trust::PINNED`.
//!
//! The release public keys used to be a hand-transcribed byte-array literal in `trust.rs`. That is
//! the wrong shape for a trust root — the bytes have a published, authoritative form (the minisign
//! `.pub` files in `Pr0j3ctPh03nix/release-tooling`, pinned by commit SHA in both workflows), and a
//! transcription of them can only ever agree with it or be silently wrong. So they are read and
//! decoded here, and the table is generated.
//!
//! **A missing or malformed key file fails the build.** There is no fallback and no empty table: a
//! launcher whose trust root is empty refuses every release, and refuses it as "no release is
//! available" (see `TrustError`), which is by design indistinguishable from an outage. Such a
//! binary must not exist, so the refusal happens here, where somebody is watching.

use std::path::{Path, PathBuf};

/// Overrides where the `.pub` files are read from. A local build points it at any
/// `release-tooling` checkout's `keys/`; CI does not set it — see `keys_dir`.
const KEYS_DIR_ENV: &str = "PHOENIX_KEYS_DIR";

/// The published keys, in the order they land in `PINNED`, each with the note it carries into the
/// generated file. Two of them, and the second is not redundant — see `trust::PINNED`.
const KEYS: [(&str, &str); 2] = [
    (
        "phoenix-active.pub",
        "ACTIVE — signs every release. Its private half is the CI signing secret, and release.yml \
         proves a freshly-made signature against this very file before it publishes anything.",
    ),
    (
        "phoenix-recovery.pub",
        "RECOVERY — the cold spare, kept offline and deliberately absent from CI, so a release it \
         signs is built and published BY HAND. A launcher accepts one only because of this entry, \
         which is why the entry exists years before it is ever used.",
    ),
];

fn main() {
    // before tauri's codegen: if this build is going to be refused, say so immediately rather than
    // after a round of work whose output is about to be thrown away
    generate_pinned_keys();
    tauri_build::build()
}

/// Decode both `.pub` files and write `$OUT_DIR/pinned_keys.rs` — the array expression that
/// `trust::PINNED` includes.
fn generate_pinned_keys() {
    let dir = keys_dir();
    // emitted for both files up front, and whether or not either can be read: a build refused for
    // a missing key has to re-run by itself once that key appears
    for (file, _) in KEYS {
        println!("cargo:rerun-if-changed={}", dir.join(file).display());
    }

    let mut out = String::from(
        "// @generated by src-tauri/build.rs — do not edit, and do not commit.\n\
         // The published release public keys, decoded from their minisign `.pub` files.\n[\n",
    );
    for (file, note) in KEYS {
        let path = dir.join(file);
        let text = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| refuse(&dir, &format!("{} cannot be read: {e}", path.display())));
        let (id, key) = parse_pub(&text).unwrap_or_else(|why| {
            refuse(&dir, &format!("{} is not a minisign public key: {why}", path.display()))
        });

        out.push_str(&comment(note));
        out.push_str(&format!("    // from {file}\n    TrustedKey {{\n"));
        out.push_str(&format!("        id: [{}],\n        key: [\n", hex_bytes(&id)));
        for row in key.chunks(8) {
            out.push_str(&format!("            {}, //\n", hex_bytes(row)));
        }
        out.push_str("        ],\n    },\n");
    }
    out.push_str("]\n");

    let dest = PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"));
    let dest = dest.join("pinned_keys.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("cannot write {}: {e}", dest.display()));
}

/// Where the `.pub` files are read from: `PHOENIX_KEYS_DIR`, else `.tooling/keys` at the repo root.
///
/// Both workflows check `release-tooling` out to exactly that path, so the default resolves in CI
/// with no per-step configuration — which matters because EVERY cargo invocation needs the keys
/// (`cargo test` compiles this crate too), not just the one that packages a release.
fn keys_dir() -> PathBuf {
    println!("cargo:rerun-if-env-changed={KEYS_DIR_ENV}");
    if let Some(dir) = std::env::var_os(KEYS_DIR_ENV) {
        return PathBuf::from(dir);
    }
    let manifest = PathBuf::from(
        std::env::var_os("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR"),
    );
    manifest
        .parent()
        .expect("src-tauri/ has a parent — this crate does not live at a filesystem root")
        .join(".tooling")
        .join("keys")
}

/// An entry's note as wrapped `//` lines. Generated or not, this file is the readable statement of
/// what the two keys are for, and a 180-column line is not one.
fn comment(note: &str) -> String {
    let (mut out, mut line) = (String::new(), String::new());
    for word in note.split_whitespace() {
        if !line.is_empty() && line.len() + 1 + word.len() > 92 {
            out.push_str(&format!("    // {line}\n"));
            line.clear();
        }
        if !line.is_empty() {
            line.push(' ');
        }
        line.push_str(word);
    }
    out + &format!("    // {line}\n")
}

/// `0xd7, 0x11, …` — the bytes only, so the caller decides the brackets.
fn hex_bytes(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("0x{b:02x}")).collect::<Vec<_>>().join(", ")
}

/// A minisign public key: an untrusted comment line, then base64 of `"Ed" || key_id || key`.
///
/// The comment is optional here and CRLF is tolerated — neither is signed, neither is an input to
/// anything, and a `.pub` that has been through a Windows editor is the ordinary case. Everything
/// the bytes actually claim IS checked: the length, the algorithm, and base64 that is exactly
/// base64.
fn parse_pub(text: &str) -> Result<([u8; 8], [u8; 32]), String> {
    let mut body = text
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with("untrusted comment:"));
    let line = body.next().ok_or("it has no key line at all")?;
    if body.next().is_some() {
        return Err("it has more than one key line".into());
    }
    let blob = b64(line).ok_or("the key line is not standard base64")?;
    if blob.len() != 42 {
        return Err(format!(
            "the key line decodes to {} bytes, not 42 (2-byte algorithm + 8-byte key id + 32-byte key)",
            blob.len()
        ));
    }
    if blob[..2] != *b"Ed" {
        return Err(format!(
            "it declares algorithm {:?}, and only \"Ed\" (pure Ed25519) is a key this launcher can verify with",
            String::from_utf8_lossy(&blob[..2])
        ));
    }
    Ok((
        blob[2..10].try_into().expect("10 - 2 == 8"),
        blob[10..].try_into().expect("42 - 10 == 32"),
    ))
}

/// Standard base64 (RFC 4648), decoded strictly — canonical padding, no whitespace, no wrapping,
/// no alternate alphabet, and no non-zero bits past the last byte. Deliberately the same
/// intolerance as `trust::b64`, and deliberately not a dependency: a build script that pulls a
/// crate in to read 56 characters has bought a supply chain for the one input whose whole job is
/// to be trustworthy.
fn b64(s: &str) -> Option<Vec<u8>> {
    let b = s.as_bytes();
    if b.is_empty() || b.len() % 4 != 0 {
        return None;
    }
    let pad = b.iter().rev().take_while(|&&c| c == b'=').count();
    if pad > 2 {
        return None;
    }
    let mut out = Vec::with_capacity(b.len() / 4 * 3);
    let (mut acc, mut bits) = (0u32, 0u32);
    for &c in &b[..b.len() - pad] {
        let v = match c {
            b'A'..=b'Z' => c - b'A',
            b'a'..=b'z' => c - b'a' + 26,
            b'0'..=b'9' => c - b'0' + 52,
            b'+' => 62,
            b'/' => 63,
            _ => return None, // including a '=' anywhere but the very end
        };
        acc = (acc << 6) | v as u32;
        bits += 6;
        if bits >= 8 {
            bits -= 8;
            out.push((acc >> bits) as u8);
        }
    }
    (acc & ((1 << bits) - 1) == 0).then_some(out)
}

/// Stop the build, saying what is wrong and what would fix it.
fn refuse(dir: &Path, problem: &str) -> ! {
    panic!(
        "\n\
         the pinned release keys could not be read, so this launcher will not be built.\n\
         \n\
         {problem}\n\
         \n\
         `trust::PINNED` is GENERATED from the published minisign public keys of\n\
         Pr0j3ctPh03nix/release-tooling. Without them there is no trust root, and a launcher with\n\
         an empty trust root refuses every release as \"no release is available\" — a silent,\n\
         permanent failure indistinguishable from an outage. It is refused here instead.\n\
         \n\
         keys directory: {}\n\
         expected in it: {}\n\
         \n\
         Both workflows check release-tooling out to `.tooling/` at the repo root, which is what\n\
         the default path points at. For a local build, point {KEYS_DIR_ENV} at any checkout:\n\
         \n\
         \x20    PHOENIX_KEYS_DIR=/path/to/release-tooling/keys cargo build\n",
        dir.display(),
        KEYS.map(|(file, _)| file).join(", "),
    )
}
